
spring:
  datasource:
    username: scs
    password: scs1234
    url: jdbc:oracle:thin:@39.101.192.246:1521/orcl.lanqiao.org
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 25
      maximum-pool-size: 30
      auto-commit: false
      idle-timeout: 30000
      pool-name: TutorialsHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL

mybatis:
  type-aliases-package: cn.edu.guet.system.model
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    context-path: /StudentCourse
logging:
  level:
    root: info
    cn.edu.guet.mapper: debug


shiro-redis:
  enable: true
  redis-manager:
    host: 127.0.0.1:6379

gljt:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: token